// iconMap.js
// Icon mapping for tool components - Material icons

import {
  IconMousePointer,
  IconMove,
  IconRotateCcw,
  IconZoomIn,
  IconPalette,
  IconCircle,
  IconCircleDot,
  IconSliders,
  IconScissors,
  IconGrid3x3,
  IconRuler,
  IconMapPin,
  IconMessageSquare,
  IconEye,
  IconEyeOff,
  IconSettings,
  IconSave,
  IconMonitor,
  IconUsers,
  IconBox,
  IconAdd,
  IconCopy,
  IconDelete,
  IconCamera,
  IconClose,
  IconMaximize,
  IconTools,
  IconLayers,
  IconRemove,
} from '@UI/react/components/common/Icon';

import {
  ExploreOutlined as IconCompass,
  SquareOutlined as IconSquare,
  ChangeHistoryOutlined as IconTriangle,
  FlipOutlined as IconFlipHorizontal,
  AutoFixHighOutlined as IconWand,
  EditOutlined as IconPenTool,
  BarChartOutlined as IconBarChart,
  ShowChartOutlined as IconActivity,
  HubOutlined as IconNetwork,
  GpsFixedOutlined as IconCrosshair,
} from '@mui/icons-material';

export const ICON_MAP = {
  "mouse-pointer": IconMousePointer,
  move: IconMove,
  "rotate-ccw": IconRotateCcw,
  "zoom-in": IconZoomIn,
  palette: IconPalette,
  circle: IconCircle,
  "circle-dot": IconCircleDot,
  sliders: IconSliders,
  scissors: IconScissors,
  "grid-3x3": IconGrid3x3,
  ruler: IconRuler,
  compass: IconCompass,
  crosshair: IconCrosshair,
  "map-pin": IconMapPin,
  square: IconSquare,
  "message-square": IconMessageSquare,
  eye: IconEye,
  "eye-off": IconEyeOff,
  settings: IconSettings,
  save: IconSave,
  monitor: IconMonitor,
  users: IconUsers,
  "pen-tool": IconPenTool,
  box: IconBox,
  plus: IconAdd,
  "flip-horizontal": IconFlipHorizontal,
  copy: IconCopy,
  "trash-2": IconDelete,
  "wand-2": IconWand,
  camera: IconCamera,
  triangle: IconTriangle,
  x: IconClose,
  "maximize-2": IconMaximize,
  "bar-chart-3": IconBarChart,
  activity: IconActivity,
  network: IconNetwork,
  transform: IconBox,
  wrench: IconTools,
  layers: IconLayers,
  minus: IconRemove,
};

export function getIcon(iconName) {
  if (!iconName) return IconBox;
  return ICON_MAP[iconName] || ICON_MAP[iconName.toLowerCase()] || IconBox;
}
